# Use config vars to get your S3 credentials onto Heroku.
# They will be automatically picked up by this file in production.

# heroku config:add S3_KEY=8N029N81 S3_SECRET=9s83109d3+583493190

# Use the following example as your guide for S3 with Paperclip.

# has_attached_file :avatar,
#   :styles         => { :thumbnail => "150x150" },
#   :path           => ":attachment/:id/:style.:extension",
#   :s3_credentials => "#{RAILS_ROOT}/config/s3.yml",

development: &default
  access_key_id: <%= ENV['S3_KEY'] %>
  secret_access_key: <%= ENV['S3_SECRET'] %>
  bucket: <%= ENV['S3_BUCKET'] %>

test:
  <<: *default

production:
  <<: *default

